### ISSUE TITLE
Store query issue in Oracle database for EI Analytics 6.5.0

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/product-ei#5503]
**Description:**
In the EI 6.5.0 analytics dashboard, when an Oracle DB is used for the EI_ANALYTICS datasource, it has been observed that the Message Latency and Message Count widgets are not populated. Furthermore, if you enable the Mediator page in the EI analytics dashboard, the same issue is observed for the widgets: Mediator Message Latency and Mediator Message Count. 

**Affected Product Version:**
EI 6.5.0

**OS, DB, other environment details and versions:**   
Oracle 12c 

**Steps to reproduce:**
Configure EI analytics and make sure to use an Oracle DB as the EI_ANALYTICS datasource.
```
  - name: EI_ANALYTICS
      description: "The datasource used for EI Analytics dashboard feature"
      jndiConfig:
        name: jdbc/EI_ANALYTICS
      definition:
        type: RDBMS
        configuration:
          jdbcUrl: 'jdbc:oracle:thin:root@//localhost:55001/ORCLCDB.localdomain'
          username: root
          password: root
          driverClassName: oracle.jdbc.driver.OracleDriver
          maxPoolSize: 50
          idleTimeout: 60000
          validationTimeout: 30000
          isAutoCommit: false
```
Add the following proxy service and sequence in the EI 
Sequence:
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="MySeq">
   <log/>
   <send>
      <endpoint>
         <address uri="http://www.mocky.io/v2/5ea2787d310000dad61ef107"/>
      </endpoint>
   </send>
</sequence>
```

Proxy service
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Textprox"
       transports="http https"
       startOnLoad="true"
       trace="enable">
   <description/>
   <target inSequence="MySeq"/>
</proxy>
```
Then invoke the proxy service using the following CURL
```
curl http://localhost:8280/services/Textprox
```
Now go to dashboard and view Sequence tab. No data is shown for Message Latency and Message Count widgets. 
Go to edit mode of the dashboard and enable Mediators page. No data is shown for Mediator-Message-Latency  and Mediator-Message-Count  widgets.
